GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Param",
    "email": "Param@mail.com",
    "gender": "Male"
}

###
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Param siap",
    "email": "Param@ggmail.com",
    "gender": "Male"
}

###
DELETE   http://localhost:5000/users/3